v-230352, idle delay setting

diff --git a/scripts/v-230229 b/scripts/v-230229
--- a/scripts/v-230229
+++ b/scripts/v-230229
@@ -1,13 +1,25 @@
 #!/bin/bash
 
-if [ -f /etc/sssd/pki/sssd_auth_ca_db.pem ]; then
-    echo "FILE EXISTS"
-else
-    echo "FILE NOT FOUND"
-    exit 1
-fi
+check_v_230229 () {
+    local finding=0
+    #CHECK config.sh for USE_PKI , SET IF APPLICABLE
+    if ! USE_PKI; then
+        echo -e "NOT APPLICABLE\nNOT USING PKI BASED AUTHENTICATION"
+        exit $finding
+    fi
 
-openssl x509 -in /etc/sssd/pki/sssd_auth_ca_db.pem -noout -issuer -subject -enddate 2>/dev/null | grep -i "dod root" || echo "DOD ROOT NOT FOUND"
+
+    if [ -f /etc/sssd/pki/sssd_auth_ca_db.pem ]; then
+        echo "FILE EXISTS"
+    else
+        echo "FILE NOT FOUND"
+        exit 1
+    fi
+
+    openssl x509 -in /etc/sssd/pki/sssd_auth_ca_db.pem -noout -issuer -subject -enddate 2>/dev/null | grep -i "dod root" || echo "DOD ROOT NOT FOUND" && finding=1
+
+    exit $finding
+}
 #
 
 #OUTPUT
