Minor

diff --git a/scripts/v-230229 b/scripts/v-230229
--- a/scripts/v-230229
+++ b/scripts/v-230229
@@ -1,5 +1,11 @@
 #!/bin/bash
 
+if [ -f /etc/sssd/pki/sssd_auth_ca_db.pem ]; then
+    echo "FILE EXISTS"
+else
+    echo "FILE NOT FOUND"
+    exit 1
+fi
 
 openssl x509 -in /etc/sssd/pki/sssd_auth_ca_db.pem -noout -issuer -subject -enddate 2>/dev/null | grep -i "dod root" || echo "DOD ROOT NOT FOUND"
 #
